apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: YWRlb2xhLm9sYWRlamk=
  GITSYNC_PASSWORD: Z2hwX0JVQXc0S1h5MkNCNHlCYmRselVhbmZPMlE2Q1p6UjQ4SElPSw==
  GIT_SYNC_USERNAME: YWRlb2xhLm9sYWRlamk=
  GIT_SYNC_PASSWORD: Z2hwX0JVQXc0S1h5MkNCNHlCYmRselVhbmZPMlE2Q1p6UjQ4SElPSw==